# Generated by Django 3.2.13 on 2022-06-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_models_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddfgghh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
